### ISSUE TITLE
Reset button not working when global search is in slots

### ISSUE THREAD

**Issue by grafxflow** [protonemedia/inertiajs-tables-laravel-query-builder#101]
When I use the global search as a slot the reset button doesn't clear the global search slot input. Yet when using the global search on the table by default it does.

The only solution that gets close is below but this causes the input value to disappear for a split second while it refreshes the value from the url.

```
<template>
  <Table>
    <template v-slot:tableGlobalSearch="slotProps">
      <input
        placeholder="Custom Global Search Component..."
        @input="slotProps.onChange($event.target.value)"
        :value="slotProps.value"
      />
    </template>
  </Table>
</template>
```

**Comment by grafxflow** [comment]
Is anybody else having the same issue?

**Comment by darkons** [comment]
Related #97

**Comment by grafxflow** [comment]
This isn't sorting the issue. Do I also need to move the reset button to a slot as well as the global search?
