### ISSUE TITLE
Is selectFilter using wildcards?

### ISSUE THREAD

**Issue by grafxflow** [protonemedia/inertiajs-tables-laravel-query-builder#102]
Is selectFilter using wildcards?

So for example if I want to use an id number such as 1 it also returns 1, 12, 21

**Comment by darkons** [comment]
Please read how Spatie's Query Builder works. This is not related to this package.

https://spatie.be/docs/laravel-query-builder/v5/features/filtering

**Comment by grafxflow** [comment]
Yes I have checked this and the solution is.

```
->allowedFilters([AllowedFilter::exact('model_id')
```
