### ISSUE TITLE
I there any way to selectFilter sort by if the value is numerical

### ISSUE THREAD

**Issue by grafxflow** [protonemedia/inertiajs-tables-laravel-query-builder#104]
I there any way to use the selectFilter and have it sortBy using the value if its numerical?

```
$table->selectFilter('language_code', [
        'en' => 'Engels',
        'nl' => 'Nederlands',
    ]);
```

So for example:

```
$table->selectFilter('model', [
        4 => 'Name1',
        1 => 'Name2',
        2 => 'Name3',
        3 => 'Name4',
    ]);
```

So it outputs:

```
<option value="1"> Name2 </option>
<option value="2"> Name3 </option>
<option value="3"> Name4 </option>
<option value="4"> Name1 </option>
```

**Comment by darkons** [comment]
Please, stop asking about things not related to this package.
If you want sort an array, just check google for help.

```php
use Illuminate\Support\Arr;

$table->selectFilter('model', Arr::sort([
    4 => 'Name1',
    1 => 'Name2',
    2 => 'Name3',
    3 => 'Name4',
]));
```

**Comment by grafxflow** [comment]
But what I am noticing is it requires the options to be an array not an object and vuejs automatically ignores all the keys no matter what order Laravel places them in and just puts them numerically.

**Comment by grafxflow** [comment]
In fact ignore it will be easier to fork and make the appropriate amends. Thanks for your help.

**Comment by darkons** [comment]
This is not my package. I'm only an user.

The options must be and array because you are working in PHP and arrays are easier to handle. Just sort your array as you want and the options will be displayed like that.

**Comment by grafxflow** [comment]
As mentioned vuejs ignores the array int key order by default for select inputs, but this package is a nice starting to expand upon.
