### ISSUE TITLE
Compatibility with Inertia.js v1

### ISSUE THREAD

**Issue by BenjaminDelacombaz** [protonemedia/inertiajs-tables-laravel-query-builder#117]
Hi,

Is it possible to migrate this package to Inertia v1 ?

Thanks in advance.

**Comment by darkons** [comment]
I am using it with Inertia v1 and I have no problems, have you had any specific problems?

However, it would be ideal to update the package for full compatibility with Inertia v1.

**Comment by thiagorsantoskpmg** [comment]
@darkons  Hello, how are you using Inertia v1?

**Comment by darkons** [comment]
Nothing special. Just upgraded my project to Inertia v1 and everything about tables still working without any changes.

**Comment by pascalbaljet** [comment]
Fixed in v2.1.0
