### ISSUE TITLE
Style broken on production build

### ISSUE THREAD

**Issue by ReinisL** [protonemedia/inertiajs-tables-laravel-query-builder#12]
Hello,

Seems like there's an issue when building assets to production. Everything looks good when running mix in the development

<img width="1002" alt="Screenshot 2021-04-27 at 09 45 06" src="https://user-images.githubusercontent.com/18574406/116197333-4f499c80-a73d-11eb-952d-cfbc4d53527b.png">

But when assets are compiled to production, it seems broken 

<img width="1006" alt="Screenshot 2021-04-27 at 09 44 42" src="https://user-images.githubusercontent.com/18574406/116197474-7a33f080-a73d-11eb-8cee-438009e9ae9b.png">

Mix also throws warning which might be related to this (Using vue3)

`[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.`

**Comment by ReinisL** [comment]
If any one has this issue I was able to fx it by updating `tailwind.config.js` file

```
module.exports = {
  purge: [
    './node_modules/@protonemedia/inertiajs-tables-laravel-query-builder/**/*.vue',
  ]
}
```

**Comment by pascalbaljet** [comment]
Thanks for noticing, I'll add a section to the docs!
