### ISSUE TITLE
⚠️ Don't start using this package for new projects

### ISSUE THREAD

**Issue by pascalbaljet** [protonemedia/inertiajs-tables-laravel-query-builder#122]
Hi everybody 👋

While I still have to make a final decision, I'll [likely abandon](https://twitter.com/pascalbaljet/status/1628173477504069632) this package. So for new projects, **don't start using it**, as you might be disappointed soon. I've put a lot of time into v1 and v2, but a few things keep me from dedicating more time to this package.

Due to circumstances, v2 never made it into one of our production apps. It was weird, but basically the moment I tagged v2, we didn't need it anymore. It also never made it into other apps. At first, I was determined to keep improving, but that's quite hard if you're not using it yourself, as there's no genuine incentive.

This package was always hard to customize for users, and it has its quirks (perhaps fundamental). Mostly, I find it hard to maintain. I have limited time available for open-source, so when I find time for it, I want to dedicate it to packages I'm really passionate about.

I'm sure some of you would've liked to see it another way. Since the package is fully open-source, you can always fork it and keep using it. Most likely, my open-source Inertia adventure ends here. 

Pascal

**Comment by nikosid** [comment]
For me this means that I'll choose the livewire stack from this moment

**Comment by nikosid** [comment]
Of should I try to use spadle?

**Comment by dsampaolo** [comment]
Hi @pascalbaljet, 

I was looking for a solution and your package seemed promising. Thank you for your time, your work, and for being honest. 

Best regards :)

**Comment by markdegrootnl** [comment]
Anybody know a good alternative?

**Comment by funkymonk91** [comment]
This is disheartening. Such a fantastic package! Thanks for everything you've done.

**Comment by Adel-Kazem** [comment]
what a loss... I really don't understand why this package didn't interest anyone as it has perfect combination .. anyway thanks for everything. The issue of this was that no one of the top gurus talked about it, anywhere I place a question about this package people come across like 'what is this?' as if it's something coming out of solar system.. the guy was making a miracle by allowing us to finally get rid of J.S. and use blade only in SPA! like wow .. anyway, God bless your nice energy, I really have no words to say rn...

**Comment by ProjectAsphaleia** [comment]
> Anybody know a good alternative?

Don't really need an alternative if you know how to program right?
Like Pascal says in the post
> Since the package is fully open-source, you can always fork it and keep using it. 

Package still works fine, probably needs a couple adjustments here and there. But imo if you're programming something and are using packages like this, you should at least know how it works and how to update it if something might be broken.

I personally just imported everything into my project and made the php side a Trait + ServiceProvider and the Vue side just goes into my components.

**Comment by hakimzulkufli** [comment]
Thanks for the great work, Pascal. I decided to make something similar for my own use internally based on your library to make it work with Svelte. It's a lot simpler and less featured than yours but it does the job.

There's a very bright future ahead for Splade and I recommend everyone giving it a try.

**Comment by pascalbaljet** [comment]
Thanks for the kind words, everybody! As expected, I'm archiving this repository to focus on [Splade](https://splade.dev) and [Eddy](https://eddy.management). 

See you around! 🙌
