### ISSUE TITLE
Mixed content when changing page in table

### ISSUE THREAD

**Issue by vpuentem** [protonemedia/inertiajs-tables-laravel-query-builder#13]
In my prod server i'm getting this error "Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS."

Probably not a bug, but can someone help me with this?

**Comment by pascalbaljet** [comment]
I'm not sure this is related to the package. Could you provide more information or code examples?

**Comment by vpuentem** [comment]
> I'm not sure this is related to the package. Could you provide more information or code examples?

I'm displaying a table with users data like below. The problem is when i try to change the page in the table i get the following error: 

Mixed Content: The page at 'https://mydomain.com/userpage?page=1&sort=-id' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mydomain.com/userspage?sort=-id&page=2'. This request has been blocked; the content must be served over HTTPS. 

`<template>
    <app-layout>
        <div class="container mx-auto py-4 px-4 sm:px-6 lg:px-8">
                <Table
                    :search="queryBuilderProps.search"
                    :columns="queryBuilderProps.columns"
                    :on-update="setQueryBuilder"
                    :meta="users"
                >
                    <template #head>
                    <tr>
                        <th @click.prevent="sortBy('id')">Id</th>
                        <th>Created at</th>
                        <th @click.prevent="sortBy('name')">Name</th>
                        <th v-show="showColumn('email')" @click.prevent="sortBy('email')">Email</th>
                    </tr>
                    </template>
                    <template #body>
                    <tr v-for="user in users.data" :key="user.id">
                        <td>{{ user.id }}</td>
                        <td>{{ new Date(Date.parse(user.created_at)).toDateString() }}</td>
                        <td>{{ user.name }}</td>
                        <td v-show="showColumn('email')">{{ user.email }}</td>
                    </tr>
                    </template>
                </Table>
            </div>
    </app-layout>
</template>

<script>
    import AppLayout from '@/Layouts/AppLayout'

    import { InteractsWithQueryBuilder, Tailwind2 } from '@protonemedia/inertiajs-tables-laravel-query-builder'

    export default {
        mixins: [InteractsWithQueryBuilder],
        props: {
            users: Object,
        },
        components: {
            AppLayout,
            Table: Tailwind2.Table
        },
    }
</script>`

I could be related to that i'm forcing https in my app service provider:

`if(env('APP_ENV') === 'production')
      {
          URL::forceScheme('https');
      }`

**Comment by vpuentem** [comment]
Was an issue with the trusted proxies in my app
