### ISSUE TITLE
Column Sort Icons

### ISSUE THREAD

**Issue by wattsie** [protonemedia/inertiajs-tables-laravel-query-builder#15]
Hi,
Wondering if you have considered adding column sort direction icon (svg)?

Or did I miss it?

Many thanks.

**Comment by luilliarcec** [comment]
I would think that they should add a method called "addSort" where you can define the columns with which you will filter and that will be sent to your view and since you already have the current order it is easy to check to which column to apply the corresponding styles and icons.

**Comment by pascalbaljet** [comment]
There'll be a `HeaderCell` component in the v1.3 release that handles column sorting and hiding for a header cell:

```vue
 <template #head>
  <tr>
    <HeaderCell :cell="sortableHeader('id')">{{ $t('ID') }}</HeaderCell>
    <HeaderCell :cell="staticHeader('customer')">{{ $t('Customer') }}</HeaderCell>
  </tr>
</template>

<script>
import { InteractsWithQueryBuilder, Tailwind2 } from '@protonemedia/inertiajs-tables-laravel-query-builder';

export default {
  mixins: [InteractsWithQueryBuilder],

  components: {
    Table: Tailwind2.Table,
    HeaderCell: Tailwind2.HeaderCell,
  },
};
</script>

Maybe I'll add another component for the `tbody` soon :)
