### ISSUE TITLE
Table Styling

### ISSUE THREAD

**Issue by wattsie** [protonemedia/inertiajs-tables-laravel-query-builder#16]
Hi,
  What is the best way to control styling.

  For example, reducing font size, line padding and so on.

  What about per column styling, for example left align, right align depending on controls?

  Would be good if styling can be "passed" to the component.

Many thanks.

Cheers.

**Comment by gregupton** [comment]
See the "Bring your own components" section of the README file.

**Comment by wattsie** [comment]
Understand, however, in the case where you may have many different table designs/layouts etc, you would have to duplicate the code multiple times. (we bow to our code duplication overlords)

Was wondering if there was a more dynamic method for applying the styles.

Cheers.

**Comment by gregupton** [comment]
Looks like that's in the roadmap... but not quite there yet.

**Comment by Adesin-fr** [comment]
Hi, 
I had a look in the current master source, and I don't see how to bring my own style, apart with replacing whole components with slots ? 
A simple and clean way would be to add classes to each part of the table (tbody , tr, td), such as inertia-table-body, inertia-table-row, inertia-table-cell, even without defining them. This way, when we want to customize one part of the table (such as padding of the cells, font size, etc...), we could just define this class in our CSS file !

I'm willing to do a PR if you think this approach is correct...

**Comment by grafxflow** [comment]
Do we have a master example of how to change each individual slot type?

**Comment by SDIjeremy** [comment]
Any update on this? I'd only like to change the Tailwind Classes. Do I have to replace all the components myself?

**Comment by anburocky3** [comment]
Following.

**Comment by SDIjeremy** [comment]
> > 
> 
> If possible, can you share the gist, so i can look it and integrate it in our app?

It's very customized to my needs, but take a look at this file from the package and modify it as you wish
https://github.com/protonemedia/inertiajs-tables-laravel-query-builder/blob/main/js/Components/Table.vue

**Comment by anburocky3** [comment]
Should i create an wrapper on top of this or? Just use the above code and link the components from this package?

**Comment by SDIjeremy** [comment]
@anburocky3 Use the above code, and remake any components that need to be restyled. Or if you feel confident you can remake the entire thing using that as reference.

**Comment by anburocky3** [comment]
Do i need to install `lodash-es`, `qs` in my project or can i reference this using the `inertiajs-tables-laravel-query-builder` package?

**Comment by anburocky3** [comment]
@SDIjeremy Did you created the customized view by creating all the Table dependency components?
