### ISSUE TITLE
Auto generation of table columns

### ISSUE THREAD

**Issue by basicmonkey** [protonemedia/inertiajs-tables-laravel-query-builder#39]
Great library, thank you!

Am I missing something or is there a way of auto generating the columns and headers based on the controller's output? The information is all in the AJAX response. This is to avoid having to statically add the template for header and body.

Many thanks,

James

**Comment by elliottcoe** [comment]
Did you ever figure this out? It doesn't seem odd that all of the columns are specified in the controller, but you have to build the table manually.

**Comment by pascalbaljet** [comment]
Fixed in v2
