### ISSUE TITLE
no way to preserveScroll

### ISSUE THREAD

**Issue by knobik** [protonemedia/inertiajs-tables-laravel-query-builder#43]
There is no way to set the "preserveScroll" property of $inertia.get() [queryBuilderData], each time i change a filter etc, the page scrolls to the top. preserveScroll should be default behavior.

this is resolved in PR #45 in the mean time i will use my own repo. Anyway awsome package!

**Comment by patrocle** [comment]
Hi,
for those who waits for this merge, make your own InteractsWithQueryBuilder : 
`  import InteractsWithQueryBuilder from '@/Components/DatatableTailwind/InteractsWithQueryBuilder';`

```
<script>
import {InteractsWithQueryBuilder,Components} from '@protonemedia/inertiajs-tables-laravel-query-builder';

export default {
    mixins: [InteractsWithQueryBuilder],
    watch: {
        queryBuilderData: {
            deep: true,
            handler() {
                if (this.$inertia) {
                    const query = this.queryBuilderString;
                    this.$inertia.get(location.pathname + `?${query}`, {}, {
                        replace: true,
                        preserveState: true,
                        preserveScroll: true
                    });
                }
            },
        },
    },
};
</script>
```

**Comment by pascalbaljet** [comment]
Fixed in v2
