### ISSUE TITLE
Vue 3: The `>>>` combinators have been deprecated

### ISSUE THREAD

**Issue by jelleroorda** [protonemedia/inertiajs-tables-laravel-query-builder#46]
When compiling the vue components, we're getting deprecation warnings for Vue 3.

![Schermafbeelding 2021-11-03 om 11 05 37](https://user-images.githubusercontent.com/9193686/140041424-c0dc1139-bae9-42b5-a748-ad59cc147ad5.png)

This seems to stem from these places:
1. [Table.vue](https://github.com/protonemedia/inertiajs-tables-laravel-query-builder/blob/main/js/Tailwind2/Table.vue#L6)
2. [Table.vue](https://github.com/protonemedia/inertiajs-tables-laravel-query-builder/blob/main/js/Tailwind2/Table.vue#L21)
3. [Table.vue](https://github.com/protonemedia/inertiajs-tables-laravel-query-builder/blob/main/js/Tailwind2/Table.vue#L33)

Can we update this to use the `:deep()` selector? Or would this be an issue for the Vue 2 build?

See also: https://v3.vuejs.org/api/sfc-style.html#style-scoped

**Comment by jonnywilliamson** [comment]
Exact same issue here.

**Comment by pascalbaljet** [comment]
Fixed in v2
