### ISSUE TITLE
Vue component doesn't work when route has parameters

### ISSUE THREAD

**Issue by eorenstein1** [protonemedia/inertiajs-tables-laravel-query-builder#5]
The Vue component throws an error when used on a route with parameters. For example, say you were using the table on the route `example.com/users/1/tasks`. When you update any of the filters or search fields and it updates the route with the new query string, it would throw the error `Error: Ziggy error: 'user' parameter is required for route 'tasks'.`

**Comment by henriquecm** [comment]
I tried overriding some methods but nothing seems to work, but pagination still works

**Comment by pascalbaljet** [comment]
Fixed in v1.1.1 😀

**Comment by eorenstein1** [comment]
Thanks for the quick fix!
