### ISSUE TITLE
How to change filter

### ISSUE THREAD

**Issue by muhammedfayaz** [protonemedia/inertiajs-tables-laravel-query-builder#65]
How to change filter '-' to 'All'?

![image](https://user-images.githubusercontent.com/105773169/172105961-96d3f839-b116-4746-9515-917e6b831c79.png)

**Comment by muhammedfayaz** [comment]
<3

**Comment by muhammedfayaz** [comment]
👍❤️ @pascalbaljet

**Comment by pascalbaljet** [comment]
Fixed in v2
