### ISSUE TITLE
Inertia.replace is deprecated

### ISSUE THREAD

**Issue by jelleroorda** [protonemedia/inertiajs-tables-laravel-query-builder#9]
Hi, thanks for this awesome package!

I'm noticing console warning from inertia about [the `replace` method being deprecated](https://inertiajs.com/releases/inertia-0.6.0#inertia-replace-deprecated). 

![Schermafbeelding 2021-04-22 om 13 11 12](https://user-images.githubusercontent.com/9193686/115705066-5dc63b80-a36c-11eb-8367-7f871fe54aab.png)

From what I can see this comes from [this line](https://github.com/protonemedia/inertiajs-tables-laravel-query-builder/blob/main/js/InteractsWithQueryBuilder.vue#L128).

**Comment by pascalbaljet** [comment]
Fixed in v1.3.3 👍
